"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const {reconcile}=require("../scripts/reconcile"),{buildReportHtml,findForbidden}=require("../scripts/build_report"),{matchProperties}=require("../scripts/property_selection");
const context={runId:"booking-test-0001",generatedAt:"2026-09-30T12:00:00-07:00",timezone:"America/Los_Angeles",skillVersion:"1.0.0",expectedProperty:{id:"42",name:"Harbor Hotel"}};
const page=(section,n,total,records=[],extra={})=>({extractionVersion:"1.0.0",section,pageNumber:n,status:extra.status||"complete",property:{id:"42",name:"Harbor Hotel"},displayedTotal:total,pagination:{hasNext:false,signature:`${section}-${n}`},records,skippedRecords:extra.skippedRecords||[],warnings:extra.warnings||[]});
test("official totals pass through without row arithmetic and both sections render",()=>{const result=reconcile([page("ready_to_charge",1,"USD 999.99",[{guestName:"Ada & Co",reservationNumber:"R1",vccExpirationDate:"10/27",rowAmount:"USD 1.00"}]),page("refund_due",1,"USD 0.00")],context);assert.equal(result.officialTotals.ready_to_charge,"USD 999.99");const html=buildReportHtml(result);assert.match(html,/Ready to Charge/);assert.match(html,/Refund Due/);assert.match(html,/USD 999\.99/);assert.match(html,/Ada &amp; Co/);});
test("skipped rows and pages are reported after upstream retry policy",()=>{const result=reconcile([page("ready_to_charge",1,"$0.00",[],{skippedRecords:[{row:2,reason:"unreadable"}]}),page("refund_due",1,"$0.00",[],{status:"page_skipped",warnings:["Unreadable after one retry"]})],context);assert.equal(result.status,"complete_with_skips");assert.equal(result.skippedRecords.length,1);assert.equal(result.skippedPages.length,1);});
test("property matching handles automatic, partial, and ambiguous selection",()=>{const ps=[{id:"1",name:"Harbor North"},{id:"2",name:"Harbor South"}];assert.equal(matchProperties([ps[0]],"").status,"selected");assert.equal(matchProperties(ps,"south").matches[0].id,"2");assert.equal(matchProperties(ps,"harbor").status,"ambiguous");});
test("sensitive keys are rejected but permitted expiration is allowed",()=>{assert.deepEqual(findForbidden({vccExpirationDate:"10/27"}),[]);assert.deepEqual(findForbidden({cardNumber:"4111"}),["cardNumber"]);});
