"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),{parseHTML}=require("linkedom");
const x=require("../scripts/browser_extract_vcc");
function doc(body,url="https://admin.booking.com/hotel/hoteladmin/extranet_ng/manage/vccs_management.html?hotel_id=285767"){const {document}=parseHTML(body);Object.defineProperty(document,"location",{value:new URL(url)});return document;}
const prop='<div data-testid="property-name">BLVD Hotel and Studios</div>';
test("parses Booking.com overview totals including US$",()=>{const d=doc(`${prop}<div><a role="tab">Virtual cards to charge</a><p>Total amount: US$5,180.12</p></div><div><a role="tab">Virtual cards to refund</a><p>Total amount: US$42</p></div>`);assert.deepEqual(x.extractOverviewTotals(d),{ready_to_charge:"US$5,180.12",refund_due:"US$42"});});
test("reads the real visible columns and ignores guest/expiration",()=>{const d=doc(`${prop}<a role="tab" aria-selected="true" aria-controls="charge">Virtual cards to charge</a><section id="charge"><table><tr><th>Cardholder</th><th>Amount</th><th>Charge before</th><th>Reservation number</th></tr><tr><td>BLVD HOTEL</td><td>US$210.50</td><td>Oct 3, 2026</td><td>445566</td></tr></table><span>1–1 of 1</span></section>`);const p=x.extractDocument(d,"ready_to_charge",1,{displayedTotal:"US$5,180.12",expectedProperty:{id:"285767",name:"BLVD Hotel and Studios"}});assert.deepEqual(p.records[0],{reservationNumber:"445566",deadline:"Oct 3, 2026",rowAmount:"US$210.50",cardholder:"BLVD HOTEL",refundReason:null});assert.equal(p.displayedTotal,"US$5,180.12");});
test("fails closed when displayed total is absent",()=>{const d=doc(`${prop}<a role="tab" aria-selected="true" aria-controls="charge">Virtual cards to charge</a><section id="charge"><p>No virtual cards</p></section>`);assert.throws(()=>x.extractDocument(d,"ready_to_charge",1,{expectedProperty:{id:"285767",name:"BLVD Hotel and Studios"}}),/displayed total is missing/);});
test("does not confuse reservation date or charged cards",()=>{assert.equal(x.classifySection("Charged cards"),null);const d=doc(`${prop}<a role="tab" aria-selected="true" aria-controls="charge">Virtual cards to charge</a><section id="charge"><table><tr><th>Reservation date</th><th>Amount</th><th>Charge before</th><th>Cardholder</th></tr></table></section>`);assert.throws(()=>x.extractDocument(d,"ready_to_charge",1,{displayedTotal:"US$1",expectedProperty:{id:"285767",name:"BLVD Hotel and Studios"}}),/reservationNumber/);});
test("scopes refund extraction to its controlled panel",()=>{const d=doc(`${prop}<a role="tab" aria-controls="charge">Virtual cards to charge</a><section id="charge"><table><tr><th>Reservation number</th></tr></table></section><a role="tab" aria-selected="true" aria-controls="refund">Virtual cards to refund</a><section id="refund"><table><tr><th>Reservation number</th><th>Refund deadline</th><th>Refund amount</th><th>Refund reason</th><th>Cardholder</th></tr><tr><td>R2</td><td>Oct 5</td><td>US$42</td><td>Overpayment</td><td>BLVD HOTEL</td></tr></table></section>`);const p=x.extractDocument(d,"refund_due",1,{displayedTotal:"US$42",expectedProperty:{id:"285767",name:"BLVD Hotel and Studios"}});assert.equal(p.records[0].reservationNumber,"R2");});
test("verifies active URL property, not first listed property",()=>{const d=doc(`${prop}<div data-property-id="111">Wrong Hotel</div><div data-property-id="285767">BLVD Hotel and Studios</div>`);assert.equal(x.verifyInteractiveSession(d,{id:"285767",name:"BLVD Hotel and Studios"}).ok,true);assert.equal(x.verifyInteractiveSession(d,{id:"111",name:"Wrong Hotel"}).ok,false);});
