(function(root){"use strict";
  const clean=v=>String(v??"").replace(/\s+/g," ").trim();
  const canon=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
  const aliases={guestName:["guest name","guest"],reservationNumber:["reservation number","booking number","confirmation number","reservation"],vccExpirationDate:["vcc expiration date","expiration date","expiry date","valid until"],rowAmount:["amount","amount to charge","refund amount","value"]};
  function index(headers,key){return headers.findIndex(h=>aliases[key].some(a=>canon(h)===a||canon(h).startsWith(a)));}
  function section(v){const s=canon(v);if(s.includes("refund due")||s.includes("refund"))return"refund_due";if(s.includes("ready to charge")||s.includes("charge"))return"ready_to_charge";return null;}
  function total(text){const matches=[...clean(text).matchAll(/\btotal\s*:?[ ]*((?:[A-Z]{3}[ ])?(?:[$€£][ ]*)?[0-9][0-9,.]*(?:[ ][A-Z]{3})?)(?![A-Za-z])/gi)];return matches.length?clean(matches[matches.length-1][1]):"";}
  function property(doc){const id=clean(doc.querySelector("[data-property-id]")?.getAttribute("data-property-id")||new URL(doc.location.href).searchParams.get("hotel_id")||new URL(doc.location.href).searchParams.get("property_id"));const name=clean(doc.querySelector("[data-testid*='property-name' i],[data-property-name],[aria-label*='property' i]")?.textContent);return{id,name};}
  function verifyInteractiveSession(doc,expected){if(doc.querySelector("input[type=password],form[action*='login' i]"))return{ok:false,reason:"login_required",properties:[]};const options=[...doc.querySelectorAll("[data-property-id]")].map(n=>({id:clean(n.getAttribute("data-property-id")),name:clean(n.textContent||n.getAttribute("data-property-name"))})).filter(p=>p.id&&p.name);const observed=property(doc);if(observed.id&&observed.name&&!options.some(p=>p.id===observed.id))options.push(observed);if(!expected)return{ok:true,reason:"property_selection_required",properties:options};return{ok:observed.id===expected.id,reason:observed.id===expected.id?"":"property_mismatch",property:observed,properties:options};}
  function extractDocument(doc,sectionName,pageNumber=1){const heading=[...doc.querySelectorAll("h1,h2,h3,h4,[role=heading]")].find(h=>section(h.textContent)===sectionName);const region=heading?.closest("section,article,[role=region]")||heading?.parentElement||doc;const table=region.querySelector("table");const totalNode=[...region.querySelectorAll("*")].find(n=>n.children.length===0&&/\btotal\b/i.test(clean(n.textContent)));const shownTotal=total(totalNode?.textContent||region.textContent)||"$0.00";if(!table){if(/no (?:virtual cards|records|results)|0\s+(?:virtual cards|records|results)/i.test(clean(region.textContent)))return{extractionVersion:"1.0.0",section:sectionName,pageNumber,status:"complete",property:property(doc),displayedTotal:shownTotal,pagination:{hasNext:false,signature:`${sectionName}:${pageNumber}:empty`},records:[],skippedRecords:[],warnings:[]};throw new Error(`Unreadable ${sectionName} page`);}
    const rows=[...table.querySelectorAll("tr")], header=rows.find(r=>r.querySelector("th"));const headers=[...(header?.querySelectorAll("th,td")||[])].map(c=>clean(c.textContent));const idx=Object.fromEntries(Object.keys(aliases).map(k=>[k,index(headers,k)]));if(Object.values(idx).some(v=>v<0))throw new Error(`Required Booking.com columns missing in ${sectionName}`);const records=[],skippedRecords=[];let rowNo=0;for(const row of rows){if(row===header)continue;const cells=[...row.querySelectorAll(":scope > td")];if(!cells.length)continue;rowNo++;const rec=Object.fromEntries(Object.entries(idx).map(([k,i])=>[k,clean(cells[i]?.textContent)]));if(Object.values(rec).some(v=>!v)){skippedRecords.push({row:rowNo,reason:"One or more permitted report fields were unreadable"});continue;}records.push(rec);}
    const next=[...region.querySelectorAll("button,a")].find(n=>/next/i.test(clean(n.textContent||n.getAttribute("aria-label"))));const hasNext=Boolean(next&&!next.disabled&&next.getAttribute("aria-disabled")!=="true");return{extractionVersion:"1.0.0",section:sectionName,pageNumber,status:"complete",property:property(doc),displayedTotal:shownTotal,pagination:{hasNext,signature:`${sectionName}:${pageNumber}:${records.map(r=>r.reservationNumber).join("|")||"none"}`},records,skippedRecords,warnings:[]};}
  root.BookingVccExtractor={extractDocument,verifyInteractiveSession};if(typeof module!=="undefined")module.exports=root.BookingVccExtractor;
})(typeof globalThis!=="undefined"?globalThis:this);
