(function(root){"use strict";
  const clean=v=>String(v??"").replace(/\s+/g," ").trim();
  const canon=v=>clean(v).toLowerCase().replace(/[?:]/g,"").replace(/\s+/g," ").trim();
  const SECTION_LABELS={ready_to_charge:["virtual cards to charge","to charge"],refund_due:["virtual cards to refund","to refund"]};
  const HEADERS={reservationNumber:["reservation number","booking number","confirmation number"],rowAmount:["amount","amount to charge","refund amount"],cardholder:["cardholder","card holder"],chargeDeadline:["charge before","charge-before date","charge by","latest charge date"],refundDeadline:["refund deadline","refund by","refund before"],refundReason:["refund reason","reason"]};
  function exactIndex(headers,key){const allowed=HEADERS[key];return headers.findIndex(h=>allowed.includes(canon(h)));}
  function classifySection(label){const value=canon(label);for(const [key,labels] of Object.entries(SECTION_LABELS))if(labels.includes(value))return key;return null;}
  function parseDisplayedTotal(text){const match=clean(text).match(/\btotal amount\s*:\s*((?:[A-Z]{2,3}\$|[A-Z]{3}\s*[$€£]?|[$€£])\s*[0-9][0-9,.]*)\b/i);return match?clean(match[1]):"";}
  function activePropertyId(doc){const url=new URL(doc.location?.href||"https://invalid.local");return clean(url.searchParams.get("hotel_id")||url.searchParams.get("property_id")||doc.documentElement?.getAttribute("data-hotel-id")||doc.querySelector("[data-current-property-id],[data-active-property-id]")?.getAttribute("data-current-property-id")||doc.querySelector("[data-active-property-id]")?.getAttribute("data-active-property-id"));}
  function activePropertyName(doc){const selectors=["[data-testid='property-name']","[data-testid='header-property-name']","[data-current-property-name]","[data-active-property-name]","[aria-current='true'][data-property-id]"];for(const selector of selectors){const node=doc.querySelector(selector);const value=clean(node?.getAttribute("data-current-property-name")||node?.getAttribute("data-active-property-name")||node?.textContent);if(value)return value;}return"";}
  function property(doc,expected){const id=activePropertyId(doc);let name=activePropertyName(doc);if(!name&&expected&&id===clean(expected.id))name=clean(expected.name);return{id,name};}
  function accessibleProperties(doc){return[...doc.querySelectorAll("[data-property-id]")].map(n=>({id:clean(n.getAttribute("data-property-id")),name:clean(n.getAttribute("data-property-name")||n.textContent)})).filter(p=>p.id&&p.name).filter((p,i,a)=>a.findIndex(x=>x.id===p.id)===i);}
  function verifyInteractiveSession(doc,expected){if(doc.querySelector("input[type=password],form[action*='login' i]"))return{ok:false,reason:"login_required",properties:[]};const observed=property(doc,expected),properties=accessibleProperties(doc);if(!expected)return{ok:Boolean(observed.id),reason:"property_selection_required",property:observed,properties};if(!observed.id)return{ok:false,reason:"property_id_missing",property:observed,properties};if(observed.id!==clean(expected.id))return{ok:false,reason:"property_mismatch",property:observed,properties};if(!observed.name)return{ok:false,reason:"property_name_missing",property:observed,properties};return{ok:true,reason:"",property:observed,properties};}
  function exactTab(doc,sectionName){const labels=SECTION_LABELS[sectionName];return[...doc.querySelectorAll("[role=tab],a,button")].find(n=>labels.includes(canon(n.textContent||n.getAttribute("aria-label"))));}
  function panelFor(doc,tab){const id=tab?.getAttribute("aria-controls");if(id)return doc.getElementById(id);if(tab?.getAttribute("href")?.startsWith("#"))return doc.querySelector(tab.getAttribute("href"));return tab?.closest("section,article,[role=region]")||null;}
  function findTable(doc,sectionName){const tab=exactTab(doc,sectionName),panel=panelFor(doc,tab);if(panel){const tables=[...panel.querySelectorAll("table")];if(tables.length===1)return{tab,panel,table:tables[0]};if(tables.length>1)throw new Error(`Ambiguous table count for ${sectionName}`);}const active=tab&&(tab.getAttribute("aria-selected")==="true"||tab.matches("[aria-current='page'],.active"));const visibleTables=[...doc.querySelectorAll("table")].filter(t=>!t.closest("[hidden],[aria-hidden='true']"));if(active&&visibleTables.length===1)return{tab,panel:doc,table:visibleTables[0]};return{tab,panel,table:null};}
  function extractOverviewTotals(doc){const result={};for(const sectionName of Object.keys(SECTION_LABELS)){const tab=exactTab(doc,sectionName);let node=tab;for(let i=0;node&&i<5;i++,node=node.parentElement){const value=parseDisplayedTotal(node.textContent);if(value){result[sectionName]=value;break;}}}const all=[...doc.querySelectorAll("*")].filter(n=>n.children.length===0&&/total amount\s*:/i.test(clean(n.textContent)));for(const node of all){const value=parseDisplayedTotal(node.textContent);if(!value)continue;let cursor=node.parentElement,found=null;for(let i=0;cursor&&i<6;i++,cursor=cursor.parentElement){found=[...cursor.querySelectorAll("h1,h2,h3,h4,[role=heading],a,button")].map(n=>classifySection(n.textContent)).find(Boolean);if(found)break;}if(found&&!result[found])result[found]=value;}return result;}
  function rangeText(rootNode){const text=clean(rootNode?.textContent);const match=text.match(/\b([0-9,]+)\s*[–-]\s*([0-9,]+)\s+of\s+([0-9,]+)\b/i);return match?match[0]:null;}
  function extractDocument(doc,sectionName,pageNumber=1,options={}){if(!SECTION_LABELS[sectionName])throw new Error(`Unknown section ${sectionName}`);const observedProperty=property(doc,options.expectedProperty);if(!observedProperty.id||!observedProperty.name)throw new Error("Active property identity is incomplete");const found=findTable(doc,sectionName),panel=found.panel||doc;const displayedTotal=clean(options.displayedTotal||extractOverviewTotals(doc)[sectionName]);if(!displayedTotal)throw new Error(`Booking.com displayed total is missing for ${sectionName}`);if(!found.table){if(/no (?:virtual cards|cards|records|results)/i.test(clean(panel.textContent)))return{extractionVersion:"2.0.0",section:sectionName,pageNumber,status:"complete",property:observedProperty,displayedTotal,pagination:{hasNext:false,signature:`${sectionName}:empty`,range:null},records:[],skippedRecords:[],warnings:[]};throw new Error(`Could not locate the active ${sectionName} table`);}
    const rows=[...found.table.querySelectorAll("tr")],header=rows.find(r=>r.querySelector("th"));if(!header)throw new Error(`Header row missing for ${sectionName}`);const headers=[...header.querySelectorAll(":scope > th,:scope > td")].map(c=>clean(c.textContent));const deadlineKey=sectionName==="ready_to_charge"?"chargeDeadline":"refundDeadline";const indexes={reservationNumber:exactIndex(headers,"reservationNumber"),deadline:exactIndex(headers,deadlineKey),rowAmount:exactIndex(headers,"rowAmount"),cardholder:exactIndex(headers,"cardholder"),refundReason:sectionName==="refund_due"?exactIndex(headers,"refundReason"):-1};for(const key of ["reservationNumber","deadline","rowAmount","cardholder"])if(indexes[key]<0)throw new Error(`Required column ${key} missing for ${sectionName}`);
    const records=[],skippedRecords=[];let rowNo=0;for(const row of rows){if(row===header)continue;const cells=[...row.querySelectorAll(":scope > td")];if(!cells.length)continue;rowNo++;const record={reservationNumber:clean(cells[indexes.reservationNumber]?.textContent),deadline:clean(cells[indexes.deadline]?.textContent),rowAmount:clean(cells[indexes.rowAmount]?.textContent),cardholder:clean(cells[indexes.cardholder]?.textContent),refundReason:indexes.refundReason>=0?clean(cells[indexes.refundReason]?.textContent)||null:null};if(!record.reservationNumber||!record.deadline||!record.rowAmount||!record.cardholder){skippedRecords.push({row:rowNo,reason:"One or more required visible fields were unreadable"});continue;}records.push(record);}
    const next=[...panel.querySelectorAll("button,a")].find(n=>/^(?:next|next page)$/i.test(clean(n.textContent||n.getAttribute("aria-label"))));const hasNext=Boolean(next&&!next.disabled&&next.getAttribute("aria-disabled")!=="true");const signature=`${sectionName}:${records.map(r=>[r.reservationNumber,r.deadline,r.rowAmount,r.cardholder,r.refundReason||""].join("~")).join("|")||"empty"}`;return{extractionVersion:"2.0.0",section:sectionName,pageNumber,status:"complete",property:observedProperty,displayedTotal,pagination:{hasNext,signature,range:rangeText(panel)},records,skippedRecords,warnings:[]};}
  function prepareSection(doc,sectionName){const tab=exactTab(doc,sectionName);if(!tab)throw new Error(`Booking.com tab missing for ${sectionName}`);if(tab.getAttribute("aria-selected")!=="true")tab.click();const panel=panelFor(doc,tab)||doc;const select=[...panel.querySelectorAll("select")].find(s=>/show|page|rows/i.test(clean(s.getAttribute("aria-label")||s.previousElementSibling?.textContent)));if(select){const numeric=[...select.options].map(o=>({o,n:Number(clean(o.value||o.textContent).match(/\d+/)?.[0])})).filter(x=>Number.isFinite(x.n)).sort((a,b)=>b.n-a.n);if(numeric.length&&select.value!==numeric[0].o.value){select.value=numeric[0].o.value;select.dispatchEvent(new Event("change",{bubbles:true}));}}return true;}
  function advanceSection(doc,sectionName){const tab=exactTab(doc,sectionName),panel=panelFor(doc,tab)||doc;const next=[...panel.querySelectorAll("button,a")].find(n=>/^(?:next|next page)$/i.test(clean(n.textContent||n.getAttribute("aria-label"))));if(!next||next.disabled||next.getAttribute("aria-disabled")==="true")return false;next.click();return true;}
  root.BookingVccExtractor={advanceSection,classifySection,extractDocument,extractOverviewTotals,parseDisplayedTotal,prepareSection,verifyInteractiveSession};if(typeof module!=="undefined")module.exports=root.BookingVccExtractor;
})(typeof globalThis!=="undefined"?globalThis:this);
