#!/usr/bin/env node
"use strict";
const fs=require("node:fs"),os=require("node:os"),path=require("node:path"),{pathToFileURL}=require("node:url"),{spawnSync}=require("node:child_process");
const {validateReconciliationResult}=require("./generated/validators");
const FORBIDDEN=/^(?:cardnumber|fullcardnumber|pan|cvv|cvc|password|mfacode|verificationcode|cookie|sessiontoken)$/i;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
function findForbidden(v,p=""){if(!v||typeof v!=="object")return[];return Object.entries(v).flatMap(([k,c])=>{const q=p?`${p}.${k}`:k;return(FORBIDDEN.test(k.replace(/[^a-z]/gi,""))?[q]:[]).concat(findForbidden(c,q));});}
function verify(data){const bad=findForbidden(data);if(bad.length)throw new Error(`Sensitive fields forbidden: ${bad.join(", ")}`);if(!validateReconciliationResult(data))throw new Error("Report input failed schema validation");return true;}
function rows(items){return items.length?items.map(r=>`<tr><td>${esc(r.guestName)}</td><td>${esc(r.reservationNumber)}</td><td>${esc(r.vccExpirationDate)}</td><td class="amt">${esc(r.rowAmount)}</td></tr>`).join(""):"<tr><td colspan=4 class=muted>No records</td></tr>";}
function skips(data){const all=[...data.skippedRecords.map(x=>`${x.section}, page ${x.page}, row ${x.row}: ${x.reason}`),...data.skippedPages.map(x=>`${x.section}, page ${x.page}: ${x.error}`)];return all.length?`<h2>Skipped Records</h2><ul>${all.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:"<h2>Skipped Records</h2><p class=muted>None</p>";}
function buildReportHtml(data){verify(data);const section=(key,title)=>`<h2>${title}</h2><div class=total>Booking.com displayed total: <strong>${esc(data.officialTotals[key]||"$0.00")}</strong></div><table><thead><tr><th>Guest</th><th>Reservation / confirmation</th><th>VCC expiration</th><th>Row amount</th></tr></thead><tbody>${rows(data.records.filter(r=>r.section===key))}</tbody></table>`;return`<!doctype html><html><head><meta charset=utf-8><title>Booking.com Virtual Card Reconciliation</title><style>@page{size:Letter;margin:.55in}*{box-sizing:border-box}body{font:10px Arial;color:#18212f}header{border-bottom:3px solid #003b95;padding-bottom:12px}h1{font-size:21px;margin:0;color:#003b95}h2{font-size:14px;color:#003b95;margin:22px 0 6px}.meta{line-height:1.5;color:#52606d}.badge{display:inline-block;background:${data.status==="complete"?"#16834a":"#a65b00"};color:white;padding:5px 9px;border-radius:12px;margin-top:8px}.total{background:#eef5ff;padding:8px;text-align:right}table{width:100%;border-collapse:collapse;margin-bottom:12px}th{background:#dbeafe;color:#003b95;text-align:left}th,td{padding:6px;border-bottom:1px solid #d7dee8}.amt{text-align:right}.muted{color:#697586;font-style:italic}footer{margin-top:22px;border-top:1px solid #ccd5df;padding-top:8px;color:#697586;font-size:8px}</style></head><body><header><h1>Booking.com Virtual Card Reconciliation</h1><div class=meta><strong>${esc(data.property.name)}</strong> (property ${esc(data.property.id)})<br>Run date/time: ${esc(data.generatedAt)} (${esc(data.timezone)}) · Run ${esc(data.runId)} · Skill v${esc(data.skillVersion)}</div><span class=badge>${data.status==="complete"?"COMPLETE":"COMPLETE WITH SKIPS"}</span></header>${section("ready_to_charge","Ready to Charge")}${section("refund_due","Refund Due")}${skips(data)}<footer>Read-only report. Official totals are copied from Booking.com’s displayed section totals and are not independently calculated or compared. No card number, CVV, credentials, MFA code, cookie, or session token is included.</footer></body></html>`;}
function renderPdf(data,out,chromium){const html=buildReportHtml(data),dir=fs.mkdtempSync(path.join(os.tmpdir(),"booking-vcc-report-")),src=path.join(dir,"report.html");try{fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(src,html,{mode:0o600});const r=spawnSync(chromium,["--headless=new","--no-sandbox","--disable-gpu","--no-pdf-header-footer",`--print-to-pdf=${path.resolve(out)}`,pathToFileURL(src).href],{encoding:"utf8",timeout:60000});if(r.status!==0||r.error)throw(r.error||new Error("Chromium PDF rendering failed"));if(fs.statSync(out).size<1000)throw new Error("PDF output is unexpectedly small");return{outputPath:out};}finally{fs.rmSync(dir,{recursive:true,force:true});}}
module.exports={buildReportHtml,findForbidden,renderPdf,verify};if(require.main===module){try{const[i,o,c]=process.argv.slice(2);if(!i||!o||!c)throw new Error("Usage: build_report.js <result.json> <output.pdf> <chromium>");process.stdout.write(JSON.stringify(renderPdf(JSON.parse(fs.readFileSync(i,"utf8")),o,c))+"\n");}catch(e){process.stderr.write(`Report generation failed: ${e.message}\n`);process.exit(1);}}
